### PR TITLE
 build all script (only .sh)

### PR DESCRIPTION
**Pull request by SushilRagoonath**
I made a simple script to compile all the examples with bash, uses mingw only on windows.Let me know if this is sloppy because I'm new to bash scripting.

### CODE REVIEW

**Comment by SushilRagoonath** [comment]
Also I named this windows mingw,but I that was before the added the rest, Sorry!

**Comment by 0undefined** [comment]
I think it would be a better option to use a dictionary instead of 3 consecutive if statements :)
something like
```bash
declare -A PLATFORM
PLATFORM[msys]="win"
PLATFORM[darwin]="osx"
PLATFORM[linux-gnu]="linux"
```
And in your for-loop replace the [bash line](https://github.com/MrFrenik/gs_examples/pull/5/files#diff-53a2ed270ba970fff63d42afd532bf4262ba4d69530d06bb7e40b273fe6e2b59R5) with `bash proc/${PLATFORM[$OSTYPE]}/*.sh`; but that's just my opinion :)

**Comment by SushilRagoonath** [comment]
I get what you mean. There is no need for the branches, I'll update it eventually

**Comment by MrFrenik** [comment]
> I get what you mean. There is no need for the branches, I'll update it eventually

Fix this up, then I'll do a merge of this. Looks good otherwise.

**Comment by SushilRagoonath** [comment]
fixed up, tested on windows

**Comment by MrFrenik** [comment]
Merged, thanks for working on this!

**Pull request merged**
